# Copyright (C) 2025 choozn
# Reference: https://wiki.hyprland.org/Configuring/Window-Rules/
# List running windows: hyprctl clients

# Window Rules
windowrule {
  name = alacritty
  float = on
  match:class = foot-float|alacritty-float
}

windowrule {
  name = nwg-displays
  float = on
  match:class = nwg-displays
}

windowrule {
  name = blueman
  float = on
  match:class = blueman-manager
}

windowrule {
  name = file-operation
  float = on
  match:title = File Operation Progress
}

windowrule {
  name = file-replace
  float = on
  match:title = Confirm to replace files
}

windowrule {
  name = viewnior
  center = on
  match:title = Viewnior
}

windowrule {
  name = firefox
  no_blur = on
  match:class = firefox
}

windowrule {
  name = zen
  no_blur = on
  match:class = zen
}


# Jackbox games
windowrule {
  name = jackbox-megapicker
  fullscreen = on
  match:class = The Jackbox Megapicker
}

windowrule {
  name = jackbox-1
  fullscreen = on
  match:class = TJPP1_OpenGL
}

windowrule {
  name = jackbox-2
  fullscreen = on
  match:class = TJPP2_OpenGL
}

windowrule {
  name = jackbox-3
  fullscreen = on
  match:class = TJPP3_OpenGL
}

windowrule {
  name = jackbox-4
  fullscreen = on
  match:class = TJPP4_OpenGL
}

windowrule {
  name = jackbox-5
  fullscreen = on
  match:class = TJPP5_OpenGL
}

windowrule {
  name = jackbox-6
  fullscreen = on
  match:class = TJPP6_OpenGL
}

windowrule {
  name = jackbox-7
  fullscreen = on
  match:class = TJPP7_OpenGL
}

windowrule {
  name = jackbox-8
  fullscreen = on
  match:class = TJPP8_OpenGL
}

windowrule {
  name = jackbox-9
  fullscreen = on
  match:class = TJPP9_OpenGL
}

windowrule {
  name = jackbox-10
  fullscreen = on
  match:class = TJPP10_OpenGL
}

# Wayland issues
windowrule {
  name = fiXWayland
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}

# Layer Rules
layerrule {
  name = waybar
  blur = on
  match:namespace = waybar
}

layerrule {
  name = hyprpicker
  no_anim = on
  match:namespace = hyprpicker
}

layerrule {
  name = selection
  no_anim = on
  match:namespace = selection
}

layerrule {
  name = vicinae
  blur = on
  ignore_alpha = 0
  match:namespace = vicinae
}

