# Eilmeldung - Bundle Config
# Copyright (C) 2026 choozn
#
# This file is part of the whisker dotfile installation.

# Header
title="Eilmeldung - RSS Reader"
bundle_id="eilmeldung"

# Packages
packages=(
    "eilmeldung-bin"
)

# Config files
# Always specify the full path, not just the folder!
files=(
    "config.toml" "$XDG_CONFIG_HOME/eilmeldung/config.toml"
)

# Pre installation
pre() {
    true
}

# Pre linking
pre_link() {
    true
}

# Post installation
post() {
    true
}
