#!/usr/bin/env bash
# Copyright (C) 2025 choozn
# Alacritty startup script

# Floating window
if [ "$1" == "-f" ]; then
    shift
    alacritty --class 'alacritty-float,alacritty-float' $@

# Fullscreen window
elif [ "$1" == "-F" ]; then
    shift
    alacritty --class 'alacritty-fullscreen,alacritty-fullscreen' \
        -o window.startup_mode="'Fullscreen'" \
        window.padding.x=30 window.padding.y=30 \
        font.size=14 $@

# Default window
else
    alacritty $@
fi
