#!/usr/bin/env bash
# Copyright (C) 2025 choozn
# Hyprpicker script

color=$(hyprpicker)
image=/tmp/${color}.png

if [[ "$color" ]]; then
    echo $color | tr -d "\n" | wl-copy
    convert -size 48x48 xc:"$color" ${image}
    notify-send -h string:x-canonical-private-synchronous:sys-notify-picker -u low -i ${image} "$color, copied to clipboard."
fi
