#!/usr/bin/env bash
# Copyright (C) 2025 choozn
# GTK theme script

theme=$(awk -F= '/^\$gtk_theme/ {gsub(/^[ \t]+|[ \t]+$/, "", $2); print $2}' "$HOME/.config/hypr/hyprtheme.conf")
gsettings set org.gnome.desktop.interface gtk-theme "$theme"
