#!/usr/bin/env bash
# Copyright (C) 2025 choozn
# Startup script

_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

# Start polkit agent
if [[ ! `pidof polkit-mate-authentication-agent-1` ]]; then
	/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
fi

# Set wallpaper
~/.config/hypr/scripts/wallpaper &

# Apply theme
~/.config/hypr/scripts/gtktheme &

# Lauch notification daemon
~/.config/hypr/scripts/notifications &

# Lauch waybar
~/.config/hypr/scripts/waybar &

# Start mpd
exec mpd &

if [ ! -f "$HOME/.config/hypr/first.start" ]; then
	alacritty --class "alacritty-float,alacritty-float" -e zsh -i -c "$HOME/.config/hypr/scripts/upgrade" &
fi
