#!/usr/bin/env bash
# Copyright (C) 2025 choozn
# Waybar startup script

CONFIG_FILE="$HOME/.config/waybar/config"
STYLE_FILE="$HOME/.config/waybar/style.css"

if [[ ! $(pidof waybar) ]]; then
    waybar --bar main-bar --log-level error --config "${CONFIG_FILE}" --style "${STYLE_FILE}"
fi
