# Jellyfin - Bundle Config
# Copyright (C) 2025 choozn
#
# This file is part of the whisker dotfile installation.

# Header
title="Jellyfin"
bundle_id="jellyfin"

# Packages
packages=(
    "jellyfin"
    "jellyfin-ffmpeg"
    "intel-media-sdk"
    "intel-gpu-tools"
    "intel-media-driver"
    "intel-compute-runtime"
    "onevpl-intel-gpu"
    "libva-intel-driver"
    "libva-utils"
)

# Config files
# Always specify the full path, not just the folder!
files=(
)

# Pre installation
pre() {
    true
}

# Pre linking
pre_link() {
    true
}

# Post installation
post() {
    sudo usermod -aG render jellyfin
    sudo usermod -aG video jellyfin
    sudo systemctl restart jellyfin
    sudo systemctl enable --now jellyfin
    sudo vainfo --display drm --device /dev/dri/renderD128
    sudo /usr/lib/jellyfin-ffmpeg/ffmpeg -hwaccels
    sudo /usr/lib/jellyfin-ffmpeg/ffmpeg -v verbose -init_hw_device vaapi=va:/dev/dri/renderD128 -init_hw_device opencl@va
}
