#!/usr/bin/env bash

request_sudo() {
    sudo -v || {
        echo "[!] Failed to gain sudo access."
        exit 1
    }
}

link_files() {
    local entries=("$@")
    local is_empty=true

    for entry in "${entries[@]}"; do
        if [[ -n "$entry" ]]; then
            is_empty=false
            break
        fi
    done

    if $is_empty; then
        echo "[!] No files to link. Skipping."
        return
    fi

    local i=0
    local total=${#entries[@]}

    while ((i < total)); do
        local origin="${bundle_path}/${entries[i]}"

        if ((i + 1 >= total)); then
            echo "[!] Missing destination for origin '${entries[i]}'. Skipping."
            break
        fi

        local destination="${entries[i + 1]}"

        if [[ -z "$origin" || -z "$destination" || "$origin" == "$destination" ]]; then
            echo "[!] Skipping invalid link entry: '${entries[i]} ${entries[i + 1]}'"
            ((i += 2))
            continue
        fi

        safe_link "$origin" "$destination"

        ((i += 2))
    done
}

print_line() {
    local term_width
    term_width=$(tput cols)
    printf '%*s\n' "$term_width" '' | tr ' ' '-'
}

print_centered_title() {
    local term_width=$(tput cols)
    local title=" $1 "
    local fill_char="-"
    local fill_len=$(((term_width - ${#title}) / 2))

    printf '%*s' "$fill_len" '' | tr ' ' "$fill_char"
    printf "%s" "$title"
    printf '%*s\n' "$fill_len" '' | tr ' ' "$fill_char"
}

safe_link() {
    local src="$1"
    local dest="$2"

    # Resolve absolute paths
    src=$(realpath "$src")
    dest=$("$dest") # Don't resolve to prevent circles
    backup_folder=$(realpath -m "$backup_folder")

    # If destination exists and is not already the right symlink
    if [ -e "$dest" ] && [ ! "$(readlink -- "$dest")" = "$src" ]; then
        local rel_path="${dest#/}" # remove leading slash for relative backup path
        local backup_path="${backup_folder}/${rel_path}"

        mkdir -p "$(dirname "$backup_path")" || {
            echo "[!] Failed to create backup directory $(dirname "$backup_path"). Exiting."
            return 1
        }

        mv "$dest" "$backup_path" || {
            echo "[!] Failed to move existing $dest to backup $backup_path."
            return 1
        }

        echo "[!] Backed up $dest to $backup_path."
    fi

    # Ensure destination directory exists
    mkdir -p "$(dirname "$dest")" || {
        echo "[!] Failed to create directory $(dirname "$dest")"
        return 1
    }

    ln -sf "$src" "$dest" || {
        echo "[!] Failed to link $dest to $src."
        return 1
    }

    echo "[✓] Linked $dest → $src. ($dest now points to $src.)"
}
