# Tmux - Bundle Config
# Copyright (C) 2026 choozn
#
# This file is part of the whisker dotfile installation.

# Header
title="Tmux - Terminal Multiplexer"
bundle_id="tmux"

# Packages
packages=(
    "tmux"
    "sesh-bin"
)

# Config files
# Always specify the full path, not just the folder!
files=(
    "tmux.conf"  "$HOME/.config/tmux/tmux.conf"
    ".tmux.conf"  "$HOME/.tmux.conf"
)

# Pre installation
pre() {
    true
}

# Pre linking
pre_link() {
    true
}

# Post installation
post() {
    git clone --depth 1 https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    ~/.tmux/plugins/tpm/scripts/install_plugins.sh
}
